channels:
  - conda-forge
dependencies:
  - websockify
  - nbgitpuller
  - pip
  - pip:
      - jupyter-desktop-server
      - PyQt5
      - guidata
      - PlotPy
      - sigima
      - PythonQwt
      - scikit-image
      - opencv-python-headless
      - PyWavelets
      - psutil
      - datalab
